import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";

const PublishSchema = z.object({
  projectId: z.string(),
  type: z.enum(["static", "dynamic"]),
  mmlHtml: z.string(),
  jsModule: z.string().optional(),
  assetManifest: z.array(z.any()).default([]),
});

function buildStaticHTML(mmlHtml: string, projectName: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${projectName} — MML Scene</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #000; color: #fff; font-family: monospace; }
    .mml-container { width: 100vw; height: 100vh; }
  </style>
</head>
<body>
  <div class="mml-container">
${mmlHtml.split("\n").map((l) => "    " + l).join("\n")}
  </div>
  <!-- MML Alpha Runtime (attach your MML runtime script here) -->
</body>
</html>`;
}

function buildDynamicPackage(
  mmlHtml: string,
  jsModule: string,
  projectName: string
): Record<string, string> {
  const packageJson = JSON.stringify(
    {
      name: projectName.toLowerCase().replace(/\s+/g, "-"),
      version: "1.0.0",
      description: "Dynamic MML scene package",
      main: "index.js",
      scripts: { start: "node index.js" },
      dependencies: { ws: "^8.16.0" },
    },
    null,
    2
  );

  const indexJs = `"use strict";
// Dynamic MML Node Package
// Generated by GEEZ MML Studio

const { createSandbox } = require('./sandbox-runtime');

const mmlBase = \`${mmlHtml.replace(/`/g, "\\`")}\`;
const jsCode = \`${jsModule.replace(/`/g, "\\`")}\`;

const { sandboxAPI, startTick, serializeState } = createSandbox((state) => {
  console.log('[MML State Update]', state.substring(0, 200));
});

const { NodeVM } = require('vm2');
const vm = new NodeVM({
  sandbox: sandboxAPI,
  require: { external: false, builtin: [] },
  eval: false,
});

vm.run(jsCode, 'mml-dynamic.js');
startTick();
console.log('Dynamic MML scene running...');
`;

  return {
    "package.json": packageJson,
    "index.js": indexJs,
    "scene.mml": mmlHtml,
    "scene.js": jsModule,
    "README.md": `# ${projectName}\n\nDynamic MML Scene generated by GEEZ MML Studio.\n\n## Run\n\`\`\`\nnpm install\nnode index.js\n\`\`\`\n`,
  };
}

export async function POST(req: NextRequest) {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const parsed = PublishSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Invalid request", details: parsed.error.flatten() },
      { status: 400 }
    );
  }

  const { type, mmlHtml, jsModule, projectId } = parsed.data;
  const projectName = `geez-scene-${projectId.slice(0, 8)}`;

  try {
    if (type === "static") {
      const html = buildStaticHTML(mmlHtml, projectName);
      const encoder = new TextEncoder();
      const bytes = encoder.encode(html);

      return new NextResponse(bytes, {
        status: 200,
        headers: {
          "Content-Type": "text/html; charset=utf-8",
          "Content-Disposition": `attachment; filename="${projectName}.html"`,
          "Content-Length": bytes.length.toString(),
        },
      });
    } else {
      // Dynamic — build a ZIP package
      const files = buildDynamicPackage(
        mmlHtml,
        jsModule || "// No JS module",
        projectName
      );

      // Dynamically import JSZip (only available if installed)
      let zipBuffer: Buffer;
      try {
        const JSZipLib = await import("jszip").then((m) => m.default || m);
        const zip = new JSZipLib();
        for (const [name, content] of Object.entries(files)) {
          zip.file(name, content);
        }
        const ab = await zip.generateAsync({ type: "nodebuffer" });
        zipBuffer = Buffer.from(ab);
      } catch {
        // Fallback: return JSON if JSZip not available
        return NextResponse.json({ files, projectName }, { status: 200 });
      }

      return new NextResponse(zipBuffer as unknown as BodyInit, {
        status: 200,
        headers: {
          "Content-Type": "application/zip",
          "Content-Disposition": `attachment; filename="${projectName}.zip"`,
        },
      });
    }
  } catch (e) {
    return NextResponse.json({ error: String(e) }, { status: 500 });
  }
}
